# Generated by Django 5.1.15 on 2026-09-24 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importjob',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='analytics.dataset'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.dataset'),
        ),
        migrations.AddField(
            model_name='reportjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics.dataset'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['user', 'date'], name='analytics_s_user_id_6b6326_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['user', 'category'], name='analytics_s_user_id_7bd0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['dataset', 'category'], name='analytics_s_dataset_44bbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['user', 'region'], name='analytics_s_user_id_3998ad_idx'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['user', 'date', 'category'], name='analytics_s_user_id_2e8259_idx'),
        ),
    ]
